_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
C:
    value: 3
architecture:
    value: |-
        DQN(
          (linear1): Linear(in_features=12, out_features=32, bias=True)
          (linear2): Linear(in_features=32, out_features=64, bias=True)
          (linear3): Linear(in_features=64, out_features=32, bias=True)
          (output): Linear(in_features=32, out_features=6, bias=True)
          (MSELoss): MSELoss()
        )
batch_size:
    value: 50
learning_rate:
    value: 0.01
